import type { GetServerSideProps, NextPage } from "next";
import Link from "next/link";
import Head from "next/head";

import { MatchesWrapper } from "../src/components/MatchesWrapper";
import styles from "../styles/Home.module.css";

const Home: NextPage = (props: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <MatchesWrapper filteredMatches={props} />

        <Link
          href={{
            pathname: `/live/${1234}`,
          }}
        >
          GOOGLE
        </Link>
      </main>

      <footer className={styles.footer}>Footer</footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const listMatches = await fetch("http://localhost:3000/api/games");

  const response = await listMatches.json();

  const { completed, unstarted } = response?.allMatches?.reduce(
    (acc: any, curr: any) => {
      acc[curr.state]?.push(curr);

      return acc;
    },
    { completed: [], unstarted: [] }
  );

  return { props: { live: response.liveMatches, completed, unstarted } };
};

export default Home;
